server:
  port: 8190
  servlet:
    context-path: /online-shop-carts
url:
  productById: http://localhost:8189/app/api/v1/products/
integrations:
  product-service:
    url: http://localhost:8189/app
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000