server:
  port: 8190
  servlet:
    context-path: /online-shop-carts
integrations:
  core-service:
    url: http://localhost:8189/online-shop-core
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000


cart-service:
  cart-prefix: productsPrefix